import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { AppInitialProps } from "next/app";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const timeZone = "Asia/Seoul";

export default async function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: string };
  pageProps: AppInitialProps;
}) {
  let dict = {};
  try {
    dict = (await import(`../../dictionaries/${lng}.json`)).default;
  } catch (e) {
    console.error(e);
  }
  return (
    <html lang={lng}>
      <body>
        <NextIntlClientProvider
          locale={lng}
          messages={dict}
          timeZone={timeZone}
        >
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
